<?php

use App\Http\Controllers\Admin\AddressController;
use App\Http\Controllers\Admin\AppController;
use App\Http\Controllers\Admin\ArticleCategoryController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\DeliveryController;
use App\Http\Controllers\Admin\DeliveryMethodController;
use App\Http\Controllers\Admin\DiscountController;
use App\Http\Controllers\Admin\DistrictController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\FilterController;
use App\Http\Controllers\Admin\InstallmentApplicationController;
use App\Http\Controllers\Admin\InstallmentPlanController;
use App\Http\Controllers\Admin\LogController;
use App\Http\Controllers\Admin\ManufacturerController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\MenuItemController;
use App\Http\Controllers\Admin\NewsletterController;
use App\Http\Controllers\Admin\OptionController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PaymentMethodController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProvinceController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\RedirectController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\ReviewController;
use App\Http\Controllers\Admin\RobotController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\Admin\TicketController;
use App\Http\Controllers\Admin\TransactionController;
use App\Http\Controllers\Admin\UnitController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VerificationController;
use App\Http\Controllers\Admin\WalletController;
use App\Http\Controllers\Admin\WarrantyController;
use Illuminate\Support\Facades\Route;

Route::resource('delivery-methods', DeliveryMethodController::class);
Route::resource('payment-methods', PaymentMethodController::class);
Route::resource('payments', 'PaymentController')->only('index');
Route::resource('transactions', TransactionController::class);
Route::get('wallets/{wallet}/transactions', [WalletController::class, 'transactions'])->name('wallets.transactions');
Route::resource('wallets', WalletController::class)->only('index');
Route::name('menus.')->group(function () {
    Route::get('menus/{menu}/items/ajax', [MenuItemController::class, 'ajax'])->name('items.ajax');
    Route::get('menus/{menu}/items', [MenuItemController::class, 'index'])->name('items.index');
    Route::get('menus/{menu}/items/create', [MenuItemController::class, 'create'])->name('items.create');
    Route::post('menus/{menu}/items', [MenuItemController::class, 'store'])->name('items.store');
    Route::get('menus/items/{item}/edit', [MenuItemController::class, 'edit'])->name('items.edit');
    Route::patch('menus/items/{item}', [MenuItemController::class, 'update'])->name('items.update');
    Route::delete('menus/items/{item}', [MenuItemController::class, 'destroy'])->name('items.destroy');
});
Route::resource('menus', MenuController::class);
Route::resource('slides', SlideController::class);
Route::get('roles/{role}/users', [RoleController::class, 'users'])->name('roles.users');
Route::resource('roles', RoleController::class)->except('show');
Route::resource('permissions', PermissionController::class)->only('update', 'edit');
Route::resource('redirects', RedirectController::class);
Route::get('users/{user}/addresses/create', [AddressController::class, 'create'])->name('users.addresses.create');
Route::post('users/{user}/addresses', [AddressController::class, 'store'])->name('users.addresses.store');
Route::get('users/{user}/addresses', [AddressController::class, 'index'])->name('users.addresses.index');
Route::resource('addresses', AddressController::class)->only(['edit', 'update', 'destroy']);
Route::resource('articles', ArticleController::class);
Route::resource('attributes', AttributeController::class);
Route::resource('banners', BannerController::class);
Route::resource('categories', CategoryController::class);
Route::resource('faqs', FaqController::class);
Route::resource('deliveries', DeliveryController::class);
Route::resource('questions', QuestionController::class);
Route::prefix('installments')->name('installments.')->group(function() {
   Route::resource('plans', InstallmentPlanController::class);
   Route::resource('applications', InstallmentApplicationController::class);
});
Route::get('users/{user}/logs', [LogController::class, 'users'])->name('users.logs');
Route::get('products/{product}/logs', [LogController::class, 'products'])->name('products.logs');
Route::resource('logs', LogController::class)->only(['index', 'show']);
Route::resource('warranties', WarrantyController::class);
Route::resource('users', UserController::class);
Route::resource('article_category', ArticleCategoryController::class);
Route::resource('discounts', DiscountController::class);
Route::get('discounts/{discount}/export', [DiscountController::class, 'export'])->name('discounts.export');
Route::resource('filters', FilterController::class);
Route::resource('manufacturers', ManufacturerController::class);
Route::resource('newsletter', NewsletterController::class);
Route::resource('options', OptionController::class);
Route::post('orders/{order}/note', [OrderController::class, 'note'])->name('orders.note');
Route::get('orders/ajax', [OrderController::class, 'ajax'])->name('orders.ajax');
Route::resource('carts', CartController::class);
Route::resource('orders', OrderController::class);
Route::get('provinces/ajax', [ProvinceController::class, 'ajax'])->name('provinces.ajax');
Route::resource('provinces', ProvinceController::class);
Route::get('cities/ajax', [CityController::class, 'ajax'])->name('cities.ajax');
Route::resource('cities', CityController::class);
Route::get('districts/ajax', [DistrictController::class, 'ajax'])->name('districts.ajax');
Route::resource('districts', DistrictController::class);
Route::post('products/{product}/update-price', [ProductController::class, 'updatePrice'])->name('products.updatePrice');
Route::post('products/{product}/update-stock', [ProductController::class, 'updateStock'])->name('products.updateStock');
Route::post('products/{product}/note', [ProductController::class, 'note'])->name('products.note');
Route::get('products/ajax/{category}/{quantity}', [ProductController::class, 'ajax'])->name('products.ajax');
Route::get('products/{product}/clone', [ProductController::class, 'clone'])->name('products.clone');
Route::post('products/{product}/clone', [ProductController::class, 'storeClone'])->name('products.store-clone');
Route::get('products/export', [ProductController::class, 'export'])->name('products.export');
Route::get('products/exportExcel', [ProductController::class, 'exportExcel'])->name('products.export.excel');
Route::get('products/import', [ProductController::class, 'import'])->name('products.import');
Route::post('products/import', [ProductController::class, 'importExcel'])->name('products.import.excel');
Route::get('products/bulk-edit', [ProductController::class, 'bulkEdit'])->name('products.bulk.edit');
Route::patch('products/bulk-import', [ProductController::class, 'bulkImport'])->name('products.bulk.import');
Route::resource('products', ProductController::class);
Route::resource('pages', PageController::class);
Route::resource('reviews', ReviewController::class);
Route::resource('robots', RobotController::class)->only(['index', 'store']);
Route::resource('comments', CommentController::class);
Route::prefix('settings')->name('settings.')->group(function() {
    Route::get('/', [SettingController::class, 'index'])->name('index');
    Route::patch('/', [SettingController::class, 'update'])->name('update');
    Route::get('socials', [SettingController::class, 'socialsIndex'])->name('socials.index');
    Route::patch('socials', [SettingController::class, 'socialsUpdate'])->name('socials.update');
    Route::get('seo', [SettingController::class, 'seoIndex'])->name('seo.index');
    Route::patch('seo', [SettingController::class, 'seoUpdate'])->name('seo.update');
    Route::get('festival', [SettingController::class, 'festivalIndex'])->name('festival.index');
    Route::patch('festival', [SettingController::class, 'festivalUpdate'])->name('festival.update');

    Route::get('installment/month', [SettingController::class, 'installmentMonthIndex'])->name('installment.month.index');
    Route::get('installment/month/create', [SettingController::class, 'installmentCreate'])->name('installment.month.create');
    Route::post('installment/month/store', [SettingController::class, 'installmentMonthStore'])->name('installment.month.store');
    Route::get('installment/month/{installment}/edit', [SettingController::class, 'installmentEdit'])->name('installment.month.edit');
    Route::put('installment/month/{installment}', [SettingController::class, 'installmentMonthUpdate'])->name('installment.month.update');
    Route::delete('installment/month/delete/{id}', [SettingController::class, 'installmentDelete'])->name('installment.month.delete');

    Route::get('installment/percent', [SettingController::class, 'installmentPercentIndex'])->name('installment.percent.index');
    Route::get('installment/percent/create', [SettingController::class, 'installmentPercentCreate'])->name('installment.percent.create');
    Route::post('installment/percent/store', [SettingController::class, 'installmentPercentStore'])->name('installment.percent.store');
    Route::get('installment/percent/{installment}/edit', [SettingController::class, 'installmentPercentEdit'])->name('installment.percent.edit');
    Route::post('installment/percent/{installment}', [SettingController::class, 'installmentPercentUpdate'])->name('installment.percent.update');
    Route::delete('installment/percent/delete/{id}', [SettingController::class, 'installmentPercentDelete'])->name('installment.percent.delete');

    Route::get('installment', [SettingController::class, 'installmentIndex'])->name('installment.index');
    Route::patch('installment', [SettingController::class, 'installmentUpdate'])->name('installment.update');
    Route::get('b2b', [SettingController::class, 'b2bIndex'])->name('b2b.index');
    Route::patch('b2b', [SettingController::class, 'b2bUpdate'])->name('b2b.update');
});
Route::get('/', [AppController::class, 'index'])->name('app.index');
Route::get('reports', [ReportController::class, 'index'])->name('reports.index');
Route::resource('tickets', TicketController::class);
Route::resource('units', UnitController::class);
Route::resource('verifications', VerificationController::class);