<?php
/*+*******************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ******************************************************************************/
require_once 'VTTokenizer.inc';
require_once 'VTParser.inc';
/**PVTPATCHER-0B22DBE74D691DEDBFB03EEF626B17AA-START-vtexpressionevaluater**/
/** Don't remove the Start and Finish Markup! Modified: 2025-01-13 15:37:07 **/
include_once 'modules/ParsVT/resources/expression_engine/VTExpressionEvaluater.inc';
/**PVTPATCHER-0B22DBE74D691DEDBFB03EEF626B17AA-FINISH**/
require_once 'VTExpressionEvaluater.inc';
?>